[package]
name = "iascar"
version = "0.1.0"
edition = "2021"
authors = ["Dominik Rusovac <dominik.rusovac@hotmail.com>"]
readme = "README.md"
description = "Rust Port of the iascar counter and transpiler"
repository = "https://github.com/drwadu/soe"
keywords = ["propositional model counting", "answer set programming", "logic programming"]
categories = ["mathematics"]
license = "LGPL-2.1"

[dependencies]
clingo = { git = "https://github.com/drwadu/clingo-rs", branch = "backport-0.6/issue43" }
rug = "1.16.0"
itertools = "0.4.9"
thiserror = "1.0.30"
rayon = "1.5"

[features]
no_overcounting = []
sequential_early_termination = []